baseURL = "https://resonantknowledgelab.org/"
languageCode = "en-us"
title = "Resonant Knowledge Lab"
theme = "clarity"
copyright = "© 2025 Resonant Knowledge Lab"
enableRobotsTXT = true

[params]
  description = "Trusted Reasoning for Living Knowledge - A Virginia-based 501(c)(3) nonprofit creating open infrastructure that enables reasoning systems like GPT and Claude to work with knowledge domains organizations choose to expose—without transferring sensitive information."
  tagline = "Trusted Reasoning for Living Knowledge"
  themeVariant = "light"
  accentColor = "#0F4C81"
  logo = "/logos/rkl-logo.png"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Programs"
    url = "/programs/"
    weight = 2
  [[menu.main]]
    name = "Data Ethics"
    url = "/data-ethics/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

